<?php
include 'include/db.php';  // your existing DB connection file

$profile_pictures = [
    '12.jpg',
    '18.jpg',
    '21.jpg',
    '31.jpg',
    '41.jpg',
    '45.jpg',
    '49.jpg',
    '57.jpg',
    '62.jpg',
    '83.jpg',
    '92.jpg'
];

$drivers = [
    [
        "first_name" => "Michael",
        "last_name" => "Adeyemi",
        "email" => "michael.adeyemi@gmail.com",
        "phone" => "+2348023456789",
        "password" => password_hash("Mich@2025!ad", PASSWORD_DEFAULT),
        "exp_years" => 9,
        "education" => "OND",
        "photo_path" => "driver/uploads/profile-pictures/12.jpg",
        "acc_num" => "6209474018",
        "acc_name" => "Michael Adeyemi",
        "nin" => "NIN89236001674",
        "bank_name" => "First Bank",
        "skills" => "Attention to Detail, Punctuality",
        "speak" => "English",
        "drive" => "Manual, Long Distance",
        "resident" => "12 Alake St, Ikeja, Lagos",
        "license_number" => "DLN1234567890",
        "about_me" => "Experienced driver with a passion for safety and punctuality.",
        "dob" => "1985-04-12",
        "profile_picture" => "driver/uploads/profile-pictures/12.jpg"
    ],
    [
        "first_name" => "Fatima",
        "last_name" => "Umar",
        "email" => "fatima.umar22@yahoo.com",
        "phone" => "+2347034567890",
        "password" => password_hash("Fat!Umar@25", PASSWORD_DEFAULT),
        "exp_years" => 7,
        "education" => "SSCE",
        "photo_path" => "driver/uploads/profile-pictures/18.jpg",
        "acc_num" => "3629934984",
        "acc_name" => "Fatima Umar",
        "nin" => "NIN30322829883",
        "bank_name" => "Zenith Bank",
        "skills" => "Customer Service, Road Safety",
        "speak" => "English, Hausa",
        "drive" => "Manual, Long Distance",
        "resident" => "7 Bello Rd, Kaduna",
        "license_number" => "DLN2233445566",
        "about_me" => "Friendly and reliable, with 7 years of professional driving experience.",
        "dob" => "1990-08-23",
        "profile_picture" => "driver/uploads/profile-pictures/18.jpg"
    ],
    [
        "first_name" => "Chinedu",
        "last_name" => "Okoro",
        "email" => "chinedu.okoro@drivermail.com",
        "phone" => "+2348098765432",
        "password" => password_hash("Chine@2025#ok", PASSWORD_DEFAULT),
        "exp_years" => 4,
        "education" => "OND",
        "photo_path" => "driver/uploads/profile-pictures/21.jpg",
        "acc_num" => "2981540296",
        "acc_name" => "Chinedu Okoro",
        "nin" => "NIN86866446889",
        "bank_name" => "Access Bank",
        "skills" => "Time Management, Navigation",
        "speak" => "English, Igbo",
        "drive" => "Manual, Long Distance",
        "resident" => "18 Zik Ave, Enugu",
        "license_number" => "DLN9988776655",
        "about_me" => "Skilled in navigation and time management, always on time.",
        "dob" => "1992-11-05",
        "profile_picture" => "driver/uploads/profile-pictures/21.jpg"
    ],
    [
        "first_name" => "Grace",
        "last_name" => "Alabi",
        "email" => "gracealabi1992@gmail.com",
        "phone" => "+2347045671234",
        "password" => password_hash("G@raceAlabi25", PASSWORD_DEFAULT),
        "exp_years" => 5,
        "education" => "B.Sc",
        "photo_path" => "driver/uploads/profile-pictures/31.jpg",
        "acc_num" => "4198557023",
        "acc_name" => "Grace Alabi",
        "nin" => "NIN40111756324",
        "bank_name" => "UBA",
        "skills" => "Defensive Driving, Route Planning",
        "speak" => "English",
        "drive" => "Manual, Long Distance",
        "resident" => "24 Unity Crescent, Ibadan",
        "license_number" => "DLN1122334455",
        "about_me" => "Defensive driver with a focus on safety and customer satisfaction.",
        "dob" => "1989-02-17",
        "profile_picture" => "driver/uploads/profile-pictures/31.jpg"
    ],
    [
        "first_name" => "Yusuf",
        "last_name" => "Ibrahim",
        "email" => "yusufdriver@gmail.com",
        "phone" => "+2348012345678",
        "password" => password_hash('Yu$Ib!2025', PASSWORD_DEFAULT),
        "exp_years" => 3,
        "education" => "HND",
        "photo_path" => "driver/uploads/profile-pictures/41.jpg",
        "acc_num" => "2209193725",
        "acc_name" => "Yusuf Ibrahim",
        "nin" => "NIN64520238590",
        "bank_name" => "GTBank",
        "skills" => "Customer Service, Road Safety",
        "speak" => "English, Hausa",
        "drive" => "Manual, Long Distance",
        "resident" => "14 Ahmadu Way, Kano",
        "license_number" => "DLN5566778899",
        "about_me" => "Excellent customer service and road safety skills.",
        "dob" => "1995-06-30",
        "profile_picture" => "driver/uploads/profile-pictures/41.jpg"
    ],
    [
        "first_name" => "Kelechi",
        "last_name" => "Eze",
        "email" => "kelechi.eze@transport.ng",
        "phone" => "+2348176543210",
        "password" => password_hash("KelEze@2025!", PASSWORD_DEFAULT),
        "exp_years" => 6,
        "education" => "B.Sc",
        "photo_path" => "driver/uploads/profile-pictures/45.jpg",
        "acc_num" => "7736924851",
        "acc_name" => "Kelechi Eze",
        "nin" => "NIN58367374983",
        "bank_name" => "First Bank",
        "skills" => "Defensive Driving, Route Planning",
        "speak" => "English, Igbo",
        "drive" => "Manual, Long Distance",
        "resident" => "33 Upper Chime, Enugu",
        "license_number" => "DLN3344556677",
        "about_me" => "Route planning expert and defensive driver.",
        "dob" => "1987-09-14",
        "profile_picture" => "driver/uploads/profile-pictures/45.jpg"
    ],
    [
        "first_name" => "Aminat",
        "last_name" => "Balogun",
        "email" => "aminat.balogun@gmail.com",
        "phone" => "+2348061122334",
        "password" => password_hash("AmiBalogun#25", PASSWORD_DEFAULT),
        "exp_years" => 2,
        "education" => "SSCE",
        "photo_path" => "driver/uploads/profile-pictures/49.jpg",
        "acc_num" => "5410932847",
        "acc_name" => "Aminat Balogun",
        "nin" => "NIN99294716348",
        "bank_name" => "Zenith Bank",
        "skills" => "Time Management, Navigation",
        "speak" => "English, Yoruba",
        "drive" => "Manual, Long Distance",
        "resident" => "9 Balogun St, Ilorin",
        "license_number" => "DLN7788990011",
        "about_me" => "Punctual and skilled in time management.",
        "dob" => "1998-12-03",
        "profile_picture" => "driver/uploads/profile-pictures/49.jpg"
    ],
    [
        "first_name" => "Samuel",
        "last_name" => "Johnson",
        "email" => "samueljohnson@ridehub.com",
        "phone" => "+2348056789012",
        "password" => password_hash("SamJ@25!ride", PASSWORD_DEFAULT),
        "exp_years" => 10,
        "education" => "M.Sc",
        "photo_path" => "driver/uploads/profile-pictures/57.jpg",
        "acc_num" => "6183029472",
        "acc_name" => "Samuel Johnson",
        "nin" => "NIN14567420938",
        "bank_name" => "Access Bank",
        "skills" => "Attention to Detail, Punctuality",
        "speak" => "English",
        "drive" => "Manual, Long Distance",
        "resident" => "88 GRA Phase II, Port Harcourt",
        "license_number" => "DLN4455667788",
        "about_me" => "Highly experienced with a focus on detail and punctuality.",
        "dob" => "1980-03-21",
        "profile_picture" => "driver/uploads/profile-pictures/57.jpg"
    ],
    [
        "first_name" => "Deborah",
        "last_name" => "Nwankwo",
        "email" => "deb.nwankwo@carservice.com",
        "phone" => "+2348120099887",
        "password" => password_hash("Deb#Nwan2025", PASSWORD_DEFAULT),
        "exp_years" => 1,
        "education" => "OND",
        "photo_path" => "driver/uploads/profile-pictures/62.jpg",
        "acc_num" => "1420384759",
        "acc_name" => "Deborah Nwankwo",
        "nin" => "NIN50839174620",
        "bank_name" => "UBA",
        "skills" => "Time Management, Navigation",
        "speak" => "English, Igbo",
        "drive" => "Manual, Long Distance",
        "resident" => "5 New Market Rd, Owerri",
        "license_number" => "DLN2233557799",
        "about_me" => "New but eager to learn and deliver great service.",
        "dob" => "2000-07-19",
        "profile_picture" => "driver/uploads/profile-pictures/62.jpg"
    ],
    [
        "first_name" => "Ibrahim",
        "last_name" => "Sule",
        "email" => "ibrahim.sule92@mail.com",
        "phone" => "+2348187654321",
        "password" => password_hash("IbSu@25Pass!", PASSWORD_DEFAULT),
        "exp_years" => 6,
        "education" => "B.Sc",
        "photo_path" => "driver/uploads/profile-pictures/83.jpg",
        "acc_num" => "3840291864",
        "acc_name" => "Ibrahim Sule",
        "nin" => "NIN77823014756",
        "bank_name" => "GTBank",
        "skills" => "Defensive Driving, Route Planning",
        "speak" => "English, Hausa",
        "drive" => "Manual, Long Distance",
        "resident" => "21 Sardauna Cres, Minna",
        "license_number" => "DLN6677889900",
        "about_me" => "Defensive driver with a strong safety record.",
        "dob" => "1988-10-11",
        "profile_picture" => "driver/uploads/profile-pictures/83.jpg"
    ]
];

foreach ($drivers as $driver) {
    $stmt = $conn->prepare("INSERT INTO drivers 
        (first_name, last_name, email, phone, password, exp_years, education, photo_path, acc_num, acc_name, nin, bank_name, skills, speak, drive, resident, license_number, about_me, dob, profile_picture)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

    $stmt->bind_param(
        "ssssisssssssssssssss",
        $driver['first_name'],
        $driver['last_name'],
        $driver['email'],
        $driver['phone'],
        $driver['password'],
        $driver['exp_years'], // integer
        $driver['education'],
        $driver['photo_path'],
        $driver['acc_num'],
        $driver['acc_name'],
        $driver['nin'],
        $driver['bank_name'],
        $driver['skills'],
        $driver['speak'],
        $driver['drive'],
        $driver['resident'],
        $driver['license_number'],
        $driver['about_me'],
        $driver['dob'],
        $driver['profile_picture']
    );

    if ($stmt->execute()) {
        echo "✅ Inserted: {$driver['first_name']} {$driver['last_name']}<br>";
    } else {
        echo "❌ Error inserting {$driver['email']}: " . $stmt->error . "<br>";
    }
}

$stmt->close();
$conn->close();
?>
